name: Release

# Run the workflow when a Pull Request is opened or when changes are pushed to master
on:
  push:
    branches: [ master ]

jobs:
  get-next-version:
    # Only release on push to master
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Release
        run: npx semantic-release --dry-run
        id: get-next-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    outputs:
      new-release-published: ${{ steps.get-next-version.outputs.new-release-published }}
      new-release-version: ${{ steps.get-next-version.outputs.new-release-version }}

  release:
    # Only release on push to master
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  docs:
    needs: [get-next-version,release]
    if: needs.get-next-version.outputs.new-release-published == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Cache storybook build
        id: storybook-build-cache
        uses: actions/cache@v3
        with:
          path: docs-build
          key: ${{ hashFiles('**/yarn.lock', '**/package.json', 'src/**', '!.storybook/image-snapshots/**' ,'.storybook/**') }}

      - name: Build Storybook
        if: steps.storybook-build-cache.outputs.cache-hit != 'true'
        run: yarn build-storybook -o ./docs-build/${{ needs.get-next-version.outputs.new-release-version }}

      - name: Generate redirect index
        env:
          VERSION: ${{ needs.get-next-version.outputs.new-release-version }}
        run: |
          yarn node ./scripts/generate-index.js

      - name: Upload Storybook artifact
        uses: actions/upload-artifact@v3
        with:
          name: storybook
          path: ./docs-build
          retention-days: 1


  deploy:
    needs: [get-next-version, docs]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Download Storybook artifact
        uses: actions/download-artifact@v3
        with:
          name: storybook

      - name: Commit storybook
        run: |
          git config --global user.name "Continuous Integration"
          git config --global user.email "username@users.noreply.github.com"
          git add -A
          git commit -m "Publish docs for ${{ needs.get-next-version.outputs.new-release-version }}"
          git push

